package(default_visibility = ["//:internal"])

load("//:defs.bzl", "proto_asset")

proto_asset(
    deps = [
        "@gs_tools//src",
        "@gs_ui//src",
        "//src/common",
        "//src/data",
        "//src/project",
        "//src/routing",
        "//src/testing",
    ])
