package(default_visibility = ["//:internal"])

load("@gs_tools//bazel/typescript:defs.bzl", "ts_binary", "ts_library")


ts_library(
    name = "test_base",
    srcs = [
      "test-base.ts"
    ],
    deps = [
      "@gs_tools//src",
    ])